#ifndef TRACKLISTVIEW_GLOBAL_H
#define TRACKLISTVIEW_GLOBAL_H

#include <qglobal.h>

#ifdef TRACKLISTVIEW_LIBRARY
#define TRACKLISTVIEW_EXPORT Q_DECL_EXPORT
#else
#define TRACKLISTVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // TRACKLISTVIEW_GLOBAL_H
